Handle field types without `help_text` as string
I was seeing `AttributeError: 'NoneType' object has no attribute 'replace'` for the call `help_text = field.help_text.replace('"', '\\"')`. Evidently some field types can have `help_text` in `field_attributes`, but `field.help_text` is still `None` (rather than an empty string). This is true in particular for `django-taggit`'s `TaggableManager`, which was the source of the error – a model that defined a `tags` field using `tags = TaggableManager(blank=True)`, which seems like a pretty common use case.